### ISSUE TITLE
Great module but how can I adapt this to FB SDK 4.x ? 

### ISSUE THREAD

**Issue by kong707** [0x0c/FacebookMessengerActivity#2]
Hi,
how can I adapt this to FB SDK 4.x ? 

Thanks in advance

**Comment by 0x0c** [comment]
Try the following operations.
1.Download source code.
2.Add `M2DFacebookMessengerActivity.h` and `M2DFacebookMessengerActivity.m`
3.Add FB SDK 4.x

I think it's not good idea because we can use Facebook Messenger activity natively.
If this idea cannot use FB SDK 4.x, please send me pull request.

Thanks ;)
